//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabasedApproach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeDetail
    {
        public int empid { get; set; }
        public string empname { get; set; }
        public Nullable<int> empsalary { get; set; }
    }
}
